#!/bin/bash
# 扫描宿主机公网 IPv4，生成 .env（IP_1..IP_N）
# 并按实际检测到的 IP 数量生成 docker-compose.yml（proxy-01..proxy-N）
# 因此既支持标准 32 卡机器，也支持任意少 IP 的机器（如 2 IP / 1 IP）
# 需以 root 运行（需安装 iproute2：ip 命令）
set -euo pipefail

cd "$(dirname "$0")"

ENV_FILE=".env"
: > "$ENV_FILE"

IPS=$(ip -4 -o addr show \
    | awk '{print $4}' | cut -d/ -f1 \
    | grep -vE '^(127\.|10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[01])\.|169\.254\.)' \
    | sort -t. -k1,1n -k2,2n -k3,3n -k4,4n)

COUNT=0
for ip in $IPS; do
    COUNT=$((COUNT + 1))
    echo "IP_${COUNT}=${ip}" >> "$ENV_FILE"
done
echo "IP_COUNT=${COUNT}" >> "$ENV_FILE"
echo "Generated ${COUNT} IPs -> ${ENV_FILE}"

if [ "$COUNT" -eq 0 ]; then
    echo "ERROR: no public IP detected on this host." >&2
    exit 1
fi

# ---- SOCKS5 访问认证凭证（首次运行自动创建；内容留空=无认证）----
CRED_FILE="socks-credentials.env"
if [ ! -f "$CRED_FILE" ]; then
    cat > "$CRED_FILE" <<'EOC'
# SOCKS5 访问认证（可选）。填写 SOCKS_USER 与 SOCKS_PASS 即启用用户名/密码认证；
# 两项留空则保持无认证模式（仅靠来源 IP / 防火墙限制）。
#
# 改密码：编辑本文件后，在每台代理机执行：
#     docker compose up -d --force-recreate
# 或在本机执行 deploy/deploy.sh 一键下发到所有机器（HAProxy 无需改动）。
#
# 可选：限定客户端来源 IP/网段（逗号分隔，如 1.2.3.4,5.6.7.0/24），留空表示不限。
SOCKS_USER=
SOCKS_PASS=
ALLOW_SRC=
EOC
    echo "Created credential template -> ${CRED_FILE}"
fi

# ---- 按实际 IP 数量生成 docker-compose.yml ----
# host 网络：每个容器绑定一个公网 IP 的 1080 端口，同机多 IP 互不冲突
COMPOSE_FILE="docker-compose.yml"
: > "$COMPOSE_FILE"

printf '# auto-generated by generate-env.sh: %s exit IP(s) on this host\n' "$COUNT" > "$COMPOSE_FILE"
printf 'services:\n' >> "$COMPOSE_FILE"

i=0
for ip in $IPS; do
    i=$((i + 1))
    name=$(printf 'proxy-%02d' "$i")
    {
        printf '  %s:\n' "$name"
        printf '    image: ${IMAGE_REPO:-ghcr.io/jushenzhidao/proxy-pool}:${IMAGE_TAG:-latest}\n'
        printf '    build: .\n'
        printf '    container_name: %s\n' "$name"
        printf '    env_file:\n'
        printf '      - ./socks-credentials.env\n'
        printf '    network_mode: host\n'
        printf '    restart: unless-stopped\n'
        printf '    logging:\n'
        printf '      driver: json-file\n'
        printf '      options:\n'
        printf '        max-size: "10m"\n'
        printf '        max-file: "3"\n'
        printf '    environment:\n'
        printf '      BIND_IP: %s\n' "$ip"
        printf '      PORT: 1080\n'
    } >> "$COMPOSE_FILE"
done

echo "Generated ${COUNT} services -> ${COMPOSE_FILE}"
